### ISSUE TITLE
support websocket connections

### ISSUE THREAD

**Issue by ryanberckmans** [mikejsavage/hirveserv#1]
I'm working on a web client that will eventually support MM Chat. However, the connection will be a websocket since it runs in the browser. Can you add a websocket handler? 

The websocket handler shouldn't assume the remote client uses MM chat, but my websocket client will use MM chat.

https://github.com/ryanberckmans/mud-client

**Comment by mikejsavage** [comment]
Pushed and completely untested. Set `wsPort` in your config to enable it. Let me know how it works!

edit: the "protocol" is called `chat`.

**Comment by ryanberckmans** [comment]
Thanks :dancer: will be at least a week before I can test; I'm going on a trip.

**Comment by mikejsavage** [comment]
noric

**Comment by mikejsavage** [comment]
.
