### ISSUE TITLE
Links to requirements and more setup instructions?

### ISSUE THREAD

**Issue by Oliver2213** [mikejsavage/hirveserv#2]
Hi
I consider myself relatively tech savvy and have worked with Lua before, however when attempting to set up this project I ran into more than one serious compilation error 
- There appears to be several versions of lua-cjson, and I'm unsure of which one to use
- Tokyo cabinet had loads of compilation errors so I eventually gave up on it
- just in general more setup instructions wouldn't go amiss, planning to recommend this to a friend and I feel like he'll struggle through compilation of the requirements like I did.
  Thanks for coding such a cool project, wish I could get it to run for me! :p

**Comment by mikejsavage** [comment]
Sorry, I didn't see this!

You should be installing the dependencies with [LuaRocks](https://luarocks.org/), which you can most likely install with your distro's package manager. You need to run `luarocks install cjson`, `luarocks install cqueues`, `luarocks install bcrypt` and `luarocks install luafilesystem`.

You've correctly identified that tokyocabinet is a pain in the ass, especially since tokyocabinet-lua isn't on luarocks or in any distro's repositories. If you can't be bothered, `mv modules/board.lua board.lua`.

You might also want to create a config.lua in the project root, and add `auth = true`. The other options are listed in `include/config.lua` but the others aren't very exciting.

**Comment by Oliver2213** [comment]
Awesome, I'll try this!

**Comment by Oliver2213** [comment]
Wanted to post this, as an exact log of the problems I encountered when building this to help others, so here we go:

I'm running Ubuntu server 15.04. Here's exactly what's happening:
With no lua packages installed, I get luarocks. This appears to install lua5.1, and liblua5.1-dev. I then try to install cjson... Here's the output:

blake@box:~$ sudo luarocks install cjson                                                                                                                                                                                                 

Error: No results matching query were found.                                                                                                                                                          

Ok... Try bcrypt...

blake@box:~$ sudo luarocks install bcrypt  
Installing https://rocks.moonscript.org/bcrypt-2.1-1.src.rock...  
Using https://rocks.moonscript.org/bcrypt-2.1-1.src.rock... switching to 'build' mode  
Warning: variable CFLAGS was not passed in build_variables  
gcc -DOPENSSL_cleanse=explicit_bzero  -D__BSD_VISIBLE -DHAVE_STRNDUP -I/usr/include/lua5.1 -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG -O0 -c -o compat/safebfuns.o compat/safebfuns.c  
gcc -DOPENSSL_cleanse=explicit_bzero  -D__BSD_VISIBLE -DHAVE_STRNDUP -I/usr/include/lua5.1 -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/bcrypt/bcrypt.o compat/bcrypt/bcrypt.c  
gcc -DOPENSSL_cleanse=explicit_bzero  -D__BSD_VISIBLE -DHAVE_STRNDUP -I/usr/include/lua5.1 -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/bcrypt/blowfish.o compat/bcrypt/blowfish.c  
gcc -DOPENSSL_cleanse=explicit_bzero  -D__BSD_VISIBLE -DHAVE_STRNDUP -I/usr/include/lua5.1 -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/arc4random/arc4random.o compat/arc4random/arc4random.c  
gcc -DOPENSSL_cleanse=explicit_bzero  -D__BSD_VISIBLE -DHAVE_STRNDUP -I/usr/include/lua5.1 -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/strlcpy.o compat/strlcpy.c  
gcc -DOPENSSL_cleanse=explicit_bzero  -D__BSD_VISIBLE -DHAVE_STRNDUP -I/usr/include/lua5.1 -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/sha/sha512.o compat/sha/sha512.c  
compat/sha/sha512.c:13:33: fatal error: openssl/opensslconf.h: No such file or directory  
 #include <openssl/opensslconf.h>  
                                 ^  
compilation terminated.  
<builtin>: recipe for target 'compat/sha/sha512.o' failed  
make: **\* [compat/sha/sha512.o] Error 1                                                                                                                                                                                                      

Error: Build error: Failed building.                                                                                                                                                      

This looked like a crypto problem, so on a hunch, I checked to see what the OpenSSL development library was called, and whether or not I had it.
After a little research, I found that, in fact, no. I didn't have it, so I installed libssl-dev and all it's dependencies

Then luarocks install bcrypt worked like a charm. 
Ok, now for cqueues. (I had tried this before installing bcrypt, and it failed to build as well... Let's see if SSL packages makes a difference:

sudo luarocks install cqueues

...

cqueues 20150907.51-0 is now built and installed in /usr/local (license: MIT/X11)                                                                                                                                                            

blake@box:~$ 

Ok... that worked nicely.
Luafilesystem compiled and installed just fine from luarocks. Now that just leaves this 'cjson' package...
Looks like luarocks has an entry for it under lua-cjson. Let's try building.

sudo luarocks install lua-cjson

...

lua-cjson 2.1.0-1 is now built and installed in /usr/local (license: MIT)                                                                                                                                                                    

blake@box:~$ 

Ok! That should be everything... Now time to clone and test...
h dear... it's looking in the lua 5.2 directory for lots and lots of thing, and I don't think moving them there would work because there built for 5.1... Gaaa!

**Comment by mikejsavage** [comment]
My bad about lua-cjson.

If ubuntu wants you to use 5.1, install libev and libev-dev and do `luarocks install lua-ev`. The last commit that worked on vanilla 5.1 is `22c4f724a17ea09b27f03f779493d5d751b31ddb`, so you'll want to check that out before you run the server.

**Comment by Oliver2213** [comment]
Yeah... Still having serious issues with this. I coppied the /usr/local/lua/5.1 directory to /usr/local/lib/lua/5.2 directory (which I had to create).
I then coppied /usr/local/share/lua/5.2 to /usr/local/share/lua/5.2 (which I also had to create.
Then, when I run main.lua, I get:

lua: error loading module '_cqueues' from file '/usr/local/lib/lua/5.2/_cqueues.so':  
        /usr/local/lib/lua/5.2/_cqueues.so: undefined symbol: luaL_prepbuffer  
stack traceback:  
        [C]: in ?  
        [C]: in function 'require'  
        /usr/local/share/lua/5.2/cqueues.lua:2: in function </usr/local/share/lua/5.2/cqueues.lua:1>  
        (...tail calls...)  
        [C]: in function 'require'  
        main.lua:3: in main chunk  
        [C]: in ?                                                                                                                                                                                                                            

Confused....

**Comment by Oliver2213** [comment]
Oh hmm. If needed I can upgrade to 5.2. THe only reason I have 5.1 is because luarocks got it.

**Comment by mikejsavage** [comment]
Don't copy the libs :p 

5.1 is fine. If you use 5.2 you have to install a different version of luarocks too, which ubuntu doesn't appear to package.

**Comment by Oliver2213** [comment]
Bla but then I'm not running latest code. That always irks me.
If I can compile a different luarocks, that's fine.

**Comment by mikejsavage** [comment]
It's on my todo list to ditch cqueues now that lua-ev works with newer luas, so you are actually future proofing.

**Comment by Oliver2213** [comment]
That doesn't help :p I'm gonna look into this 5.2 supporting luarocks, I don't want 6 month old code heh.

**Comment by Oliver2213** [comment]
Wow thanks for all the help, got it working! :)
I'm already playing with different modules and planning some very, very elaborate mud bots. One question though, Does hirveserv have any kind of version numbering system? I'm setting it up so all my scripts will handle it's commands as long as they know a certain chat connection is hirveserv, but I'm going to have that trigger off of it's version.

Thanks again for all the help.

**Comment by mikejsavage** [comment]
It doesn't, but you can drop something like:

```
local pipe = io.popen( "git rev-list HEAD --count" )
chat.version = pipe:read( "*all" ):trim()
pipe:close()
```

after the `require( "include.utils" )` line in main.lua to get a monotonic number.

I guess you would want to send it to clients too? Adding `self:send( "version", "hirveserv " .. chat.version )` after the setmetatable line in include/client.lua should work.

**Comment by Oliver2213** [comment]
Again, wow thanks!
I had made a version module that listened for a connection and sent just "herveserv running " ._VERSION

Not sure if I should keep asking questions on this issue, but...

If I define my own message type numbers in protocols/mm.lua, I know I can do stuff like client:send("myNewMessageType", "data")
Within a function that gets passed a client.
However, if I wanted to run a function whenever a message of that type gets received... Would I do something like

client:onCommand("MyNewType", arg1, arg2)?
I know there's some kind of event system, as well as prompts and handlers, but I can't find any sort of documentation so I've been trying things out to see what I get.

**Comment by mikejsavage** [comment]
Clients have a stack of coroutines ("handlers" :d) which accept a set of commands. When a message comes in, it gets passed to the topmost handler that cares about it. e.g in modules/editor.lua:

```
chat.handler( "editor", { "pm" }, function( ... )
    ....
    while true do
        local command, args = coroutine.yield() -- command is always going to be "pm"
        ...
    end
end )
```

The "editor" handler only cares about private messages, so anything else gets sent further down the stack. If a command reaches the bottom, it gets discarded.

You can start a new handler with client:pushHandler, or client:replaceHandler if you don't like the existing one anymore. I forget the exact semantics of replaceHandler if you aren't at the top of the stack but it's not a very useful command anyway.

**Comment by Oliver2213** [comment]
Ah... I think I understand.
What if I wanted to keep the normal chat handler, but run a function if a certain incomming message type is received.
I see in include/client.lua, it does Client:onCommand, but I didn't know if I could listen for an event with the same name as my message type in protocolls/mm.lua

**Comment by Oliver2213** [comment]
Also, (sorry for all the questions), I'm using mush client's chat plugin with this server.
Normally, to send a chat message, you do #chat nickname message
This uses the personal chat message type, but for some reason this isn't noticing the chatserver's connection.
It shows up on the list of chats, has an ID and a nickname (and now a version)... 
I know this is most likely a mush problem, but can you think of anything this server doesn't send, or sends in a different format?
There both using the mudmaster protocol.

**Comment by mikejsavage** [comment]
You would make a handler that only cares about your new command, and call pushHandler when you want to start listening.

The name crap started happening with the switch to cqueues, and I have no idea what causes it. It's one of the reasons I want to switch back to lua-ev.

**Comment by Oliver2213** [comment]
Yeah that's weird... I was going to update the mush chat plugin to work around this somehow, when I thought it was some piece of information I thought hirve wasn't sending.
I don't know enough about lua socket / TCP IP stuff to help, otherwise I would, it's quite annoying having to send chat commands from a scripting window.

**Comment by mikejsavage** [comment]
As a heads up incase you are still using this - I finally got around to dropping cqueues/tokyocabinet
